# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e8638f98eb444530a0ec89af34bc970c829d263942305c86feff53041fa7a6dd48fc42ee382e03fc8b5fce24d2c735aaf1877697eb93f226e2213f50c6ec339

test:
  secret_key_base: 7ffb4753b7cdeb7d8e79990d47045c30e9d3a13f7e671557b0a19bb4cc11071336e31452f4f23c76436174cf2ed8382f3da44ca244bf98f9d8219fd4f2175a9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
